package com.woniu.mapper;

import com.woniu.pojo.Rwp;
import com.woniu.pojo.RwpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RwpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	long countByExample(RwpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	int deleteByExample(RwpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	int deleteByPrimaryKey(Integer rwpid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	int insert(Rwp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	int insertSelective(Rwp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	List<Rwp> selectByExample(RwpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	Rwp selectByPrimaryKey(Integer rwpid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	int updateByExampleSelective(@Param("record") Rwp record, @Param("example") RwpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	int updateByExample(@Param("record") Rwp record, @Param("example") RwpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	int updateByPrimaryKeySelective(Rwp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rwp
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	int updateByPrimaryKey(Rwp record);
}