package com.woniu.pojo;

public class Powers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column powers.pid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column powers.pmark
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private String pmark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column powers.pid
	 * @return  the value of powers.pid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column powers.pid
	 * @param pid  the value for powers.pid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column powers.pmark
	 * @return  the value of powers.pmark
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public String getPmark() {
		return pmark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column powers.pmark
	 * @param pmark  the value for powers.pmark
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setPmark(String pmark) {
		this.pmark = pmark;
	}
}