package com.woniu.pojo;

public class Rwp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rwp.rwpid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private Integer rwpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rwp.ridd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private Integer ridd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rwp.pidd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private Integer pidd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rwp.rwpid
	 * @return  the value of rwp.rwpid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Integer getRwpid() {
		return rwpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rwp.rwpid
	 * @param rwpid  the value for rwp.rwpid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setRwpid(Integer rwpid) {
		this.rwpid = rwpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rwp.ridd
	 * @return  the value of rwp.ridd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Integer getRidd() {
		return ridd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rwp.ridd
	 * @param ridd  the value for rwp.ridd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setRidd(Integer ridd) {
		this.ridd = ridd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rwp.pidd
	 * @return  the value of rwp.pidd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Integer getPidd() {
		return pidd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rwp.pidd
	 * @param pidd  the value for rwp.pidd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setPidd(Integer pidd) {
		this.pidd = pidd;
	}
}