package com.woniu.pojo;

import java.util.ArrayList;
import java.util.List;

public class UsersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public UsersExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(Integer value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(Integer value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<Integer> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUpwdIsNull() {
			addCriterion("upwd is null");
			return (Criteria) this;
		}

		public Criteria andUpwdIsNotNull() {
			addCriterion("upwd is not null");
			return (Criteria) this;
		}

		public Criteria andUpwdEqualTo(String value) {
			addCriterion("upwd =", value, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdNotEqualTo(String value) {
			addCriterion("upwd <>", value, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdGreaterThan(String value) {
			addCriterion("upwd >", value, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdGreaterThanOrEqualTo(String value) {
			addCriterion("upwd >=", value, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdLessThan(String value) {
			addCriterion("upwd <", value, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdLessThanOrEqualTo(String value) {
			addCriterion("upwd <=", value, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdLike(String value) {
			addCriterion("upwd like", value, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdNotLike(String value) {
			addCriterion("upwd not like", value, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdIn(List<String> values) {
			addCriterion("upwd in", values, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdNotIn(List<String> values) {
			addCriterion("upwd not in", values, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdBetween(String value1, String value2) {
			addCriterion("upwd between", value1, value2, "upwd");
			return (Criteria) this;
		}

		public Criteria andUpwdNotBetween(String value1, String value2) {
			addCriterion("upwd not between", value1, value2, "upwd");
			return (Criteria) this;
		}

		public Criteria andUnameIsNull() {
			addCriterion("uname is null");
			return (Criteria) this;
		}

		public Criteria andUnameIsNotNull() {
			addCriterion("uname is not null");
			return (Criteria) this;
		}

		public Criteria andUnameEqualTo(String value) {
			addCriterion("uname =", value, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameNotEqualTo(String value) {
			addCriterion("uname <>", value, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameGreaterThan(String value) {
			addCriterion("uname >", value, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameGreaterThanOrEqualTo(String value) {
			addCriterion("uname >=", value, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameLessThan(String value) {
			addCriterion("uname <", value, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameLessThanOrEqualTo(String value) {
			addCriterion("uname <=", value, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameLike(String value) {
			addCriterion("uname like", value, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameNotLike(String value) {
			addCriterion("uname not like", value, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameIn(List<String> values) {
			addCriterion("uname in", values, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameNotIn(List<String> values) {
			addCriterion("uname not in", values, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameBetween(String value1, String value2) {
			addCriterion("uname between", value1, value2, "uname");
			return (Criteria) this;
		}

		public Criteria andUnameNotBetween(String value1, String value2) {
			addCriterion("uname not between", value1, value2, "uname");
			return (Criteria) this;
		}

		public Criteria andUroleIsNull() {
			addCriterion("urole is null");
			return (Criteria) this;
		}

		public Criteria andUroleIsNotNull() {
			addCriterion("urole is not null");
			return (Criteria) this;
		}

		public Criteria andUroleEqualTo(String value) {
			addCriterion("urole =", value, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleNotEqualTo(String value) {
			addCriterion("urole <>", value, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleGreaterThan(String value) {
			addCriterion("urole >", value, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleGreaterThanOrEqualTo(String value) {
			addCriterion("urole >=", value, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleLessThan(String value) {
			addCriterion("urole <", value, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleLessThanOrEqualTo(String value) {
			addCriterion("urole <=", value, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleLike(String value) {
			addCriterion("urole like", value, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleNotLike(String value) {
			addCriterion("urole not like", value, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleIn(List<String> values) {
			addCriterion("urole in", values, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleNotIn(List<String> values) {
			addCriterion("urole not in", values, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleBetween(String value1, String value2) {
			addCriterion("urole between", value1, value2, "urole");
			return (Criteria) this;
		}

		public Criteria andUroleNotBetween(String value1, String value2) {
			addCriterion("urole not between", value1, value2, "urole");
			return (Criteria) this;
		}

		public Criteria andUemailIsNull() {
			addCriterion("uemail is null");
			return (Criteria) this;
		}

		public Criteria andUemailIsNotNull() {
			addCriterion("uemail is not null");
			return (Criteria) this;
		}

		public Criteria andUemailEqualTo(String value) {
			addCriterion("uemail =", value, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailNotEqualTo(String value) {
			addCriterion("uemail <>", value, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailGreaterThan(String value) {
			addCriterion("uemail >", value, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailGreaterThanOrEqualTo(String value) {
			addCriterion("uemail >=", value, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailLessThan(String value) {
			addCriterion("uemail <", value, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailLessThanOrEqualTo(String value) {
			addCriterion("uemail <=", value, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailLike(String value) {
			addCriterion("uemail like", value, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailNotLike(String value) {
			addCriterion("uemail not like", value, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailIn(List<String> values) {
			addCriterion("uemail in", values, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailNotIn(List<String> values) {
			addCriterion("uemail not in", values, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailBetween(String value1, String value2) {
			addCriterion("uemail between", value1, value2, "uemail");
			return (Criteria) this;
		}

		public Criteria andUemailNotBetween(String value1, String value2) {
			addCriterion("uemail not between", value1, value2, "uemail");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 09 10:38:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}