package com.woniu.pojo;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.uid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.upwd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private String upwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.uname
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private String uname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.urole
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private String urole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.uemail
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private String uemail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.uid
	 * @return  the value of users.uid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.uid
	 * @param uid  the value for users.uid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.upwd
	 * @return  the value of users.upwd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public String getUpwd() {
		return upwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.upwd
	 * @param upwd  the value for users.upwd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.uname
	 * @return  the value of users.uname
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public String getUname() {
		return uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.uname
	 * @param uname  the value for users.uname
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.urole
	 * @return  the value of users.urole
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public String getUrole() {
		return urole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.urole
	 * @param urole  the value for users.urole
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setUrole(String urole) {
		this.urole = urole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.uemail
	 * @return  the value of users.uemail
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public String getUemail() {
		return uemail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.uemail
	 * @param uemail  the value for users.uemail
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setUemail(String uemail) {
		this.uemail = uemail;
	}
}