package com.woniu.pojo;

public class Uwr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uwr.uwrid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private Integer uwrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uwr.uidd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private Integer uidd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uwr.ridd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	private Integer ridd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uwr.uwrid
	 * @return  the value of uwr.uwrid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Integer getUwrid() {
		return uwrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uwr.uwrid
	 * @param uwrid  the value for uwr.uwrid
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setUwrid(Integer uwrid) {
		this.uwrid = uwrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uwr.uidd
	 * @return  the value of uwr.uidd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Integer getUidd() {
		return uidd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uwr.uidd
	 * @param uidd  the value for uwr.uidd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setUidd(Integer uidd) {
		this.uidd = uidd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uwr.ridd
	 * @return  the value of uwr.ridd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public Integer getRidd() {
		return ridd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uwr.ridd
	 * @param ridd  the value for uwr.ridd
	 * @mbg.generated  Tue Jun 09 11:11:57 CST 2020
	 */
	public void setRidd(Integer ridd) {
		this.ridd = ridd;
	}
}